export default country =[
    {country: "Iran", code: "98", label: "ir"},
    {country: "Iraq", code: "964", label: "iq"},
    {country: "Ireland", code: "353", label: "ie"},
    {country: "Israel", code: "972", label: "il"},
    {country: "Italy", code: "39", label: "it"},
    {country: "Jamaica", code: "1-876", label: "jm"},
    {country: "Japan", code: "81", label: "jp"},
    {country: "Jordan", code: "962", label: "jo"},
    {country: "Kazakhstan", code: "7", label: "kz"},
    {country: "Kenya", code: "254", label: "ke"},
    {country: "Kiribati", code: "686", label: "ki"},
    {country: "Korea, North", code: "850", label: "kp"},
    {country: "Korea, South", code: "82", label: "kr"},
    {country: "Kuwait", code: "965", label: "kw"},
    {country: "Kyrgyzstan", code: "996", label: "kg"},
    {country: "Lao People's Democratic Republic", code: "856", label: "la"},
    {country: "Latvia", code: "371", label: "lv"},
    {country: "Lebanon", code: "961", label: "lb"},
    {country: "Lesotho", code: "266", label: "ls"},
    {country: "Liberia", code: "231", label: "lr"},
    {country: "Libya", code: "218", label: "ly"},
    {country: "Liechtenstein", code: "423", label: "li"},
    {country: "Lithuania", code: "370", label: "lt"},
    {country: "Luxembourg", code: "352", label: "lu"},
    {country: "Madagascar", code: "261", label: "mg"},
    {country: "Malawi", code: "265", label: "mw"},
    {country: "Malaysia", code: "60", label: "my"},
    {country: "Maldives", code: "960", label: "mv"},
    {country: "Mali", code: "223", label: "ml"},
    {country: "Malta", code: "356", label: "mt"},
    {country: "Marshall Islands", code: "692", label: "mh"},
    {country: "Martinique", code: "596", label: "mq"},
    {country: "Mauritania", code: "222", label: "mr"},
    {country: "Mauritius", code: "230", label: "mu"},
    {country: "Mayotte", code: "262", label: "yt"},
    {country: "Mexico", code: "52", label: "mx"},
    {country: "Micronesia", code: "691", label: "fm"},
    {country: "Moldova", code: "373", label: "md"},
    {country: "Monaco", code: "377", label: "mc"},
    {country: "Mongolia", code: "976", label: "mn"},
    {country: "Montenegro", code: "382", label: "me"},
    {country: "Morocco", code: "212", label: "ma"},
    {country: "Mozambique", code: "258", label: "mz"},
    {country: "Myanmar", code: "95", label: "mm"},
    {country: "Namibia", code: "264", label: "na"},
    {country: "Nauru", code: "674", label: "nr"},
    {country: "Nepal", code: "977", label: "np"},
    {country: "Netherlands", code: "31", label: "nl"},
    {country: "New Caledonia", code: "687", label: "nc"},
    {country: "New Zealand", code: "64", label: "nz"},
    {country: "Nicaragua", code: "505", label: "ni"},
    {country: "Niger", code: "227", label: "ne"},
    {country: "Nigeria", code: "234", label: "ng"},
    {country: "Niue", code: "683", label: "nu"},
    {country: "Norfolk Island", code: "672", label: "nf"},
    {country: "North Macedonia", code: "389", label: "mk"},
    {country: "Northern Mariana Islands", code: "1-670", label: "mp"},
    {country: "Norway", code: "47", label: "no"},
    {country: "Oman", code: "968", label: "om"},
    {country: "Pakistan", code: "92", label: "pk"},
    {country: "Palau", code: "680", label: "pw"},
    {country: "Palestine", code: "970", label: "ps"},
    {country: "Panama", code: "507", label: "pa"},
    {country: "Papua New Guinea", code: "675", label: "pg"},
    {country: "Paraguay", code: "595", label: "py"},
    {country: "Peru", code: "51", label: "pe"},
    {country: "Philippines", code: "63", label: "ph"},
    {country: "Pitcairn", code: "64", label: "pn"},
    {country: "Poland", code: "48", label: "pl"},
    {country: "Portugal", code: "351", label: "pt"},
    {country: "Puerto Rico", code: "1-787, 1-939", label: "pr"},
    {country: "Qatar", code: "974", label: "qa"},
    {country: "Romania", code: "40", label: "ro"},
    {country: "Russia", code: "7", label: "ru"},
    {country: "Rwanda", code: "250", label: "rw"},
    {country: "Réunion", code: "262", label: "re"},
    {country: "Saint Barthelemy", code: "590", label: "bl"},
    {country: "Saint Helena", code: "290", label: "sh"},
    {country: "Saint Kitts and Nevis", code: "1-869", label: "kn"},
    {country: "Saint Lucia", code: "1-758", label: "lc"},
    {country: "Saint Martin", code: "590", label: "mf"},
    {country: "Saint Pierre and Miquelon", code: "508", label: "pm"},
    {country: "Saint Vincent and the Grenadines", code: "1-784", label: "vc"},
    {country: "Samoa", code: "685", label: "ws"},
    {country: "San Marino", code: "378", label: "sm"},
    {country: "Sao Tome and Principe", code: "239", label: "st"},
    {country: "Saudi Arabia", code: "966", label: "sa"},
    {country: "Senegal", code: "221", label: "sn"},
    {country: "Serbia", code: "381", label: "rs"},
    {country: "Seychelles", code: "248", label: "sc"},
    {country: "Sierra Leone", code: "232", label: "sl"},
    {country: "Singapore", code: "65", label: "sg"},
    {country: "Sint Maarten", code: "1-721", label: "sx"},
    {country: "Slovakia", code: "421", label: "sk"},
    {country: "Slovenia", code: "386", label: "si"},
    {country: "Solomon Islands", code: "677", label: "sb"},
    {country: "Somalia", code: "252", label: "so"},
    {country: "South Africa", code: "27", label: "za"},
    {country: "South Korea", code: "82", label: "kr"},
    {country: "South Sudan", code: "211", label: "ss"},
    {country: "Spain", code: "34", label: "es"},
    {country: "Sri Lanka", code: "94", label: "lk"},
    {country: "Sudan", code: "249", label: "sd"},
    {country: "Suriname", code: "597", label: "sr"},
    {country: "Svalbard and Jan Mayen", code: "47", label: "sj"},
    {country: "Sweden", code: "46", label: "se"},
    {country: "Switzerland", code: "41", label: "ch"},
    {country: "Syria", code: "963", label: "sy"},
    {country: "Taiwan", code: "886", label: "tw"},
    {country: "Tajikistan", code: "992", label: "tj"},
    {country: "Tanzania", code: "255", label: "tz"},
    {country: "Thailand", code: "66", label: "th"},
    {country: "Togo", code: "228", label: "tg"},
    {country: "Tokelau", code: "690", label: "tk"},
    {country: "Tonga", code: "676", label: "to"},
    {country: "Trinidad and Tobago", code: "1-868", label: "tt"},
    {country: "Tunisia", code: "216", label: "tn"},
    {country: "Turkey", code: "90", label: "tr"},
    {country: "Turkmenistan", code: "993", label: "tm"},
    {country: "Turks and Caicos Islands", code: "1-649", label: "tc"},
    {country: "Tuvalu", code: "688", label: "tv"},
    {country: "U.S. Virgin Islands", code: "1-340", label: "vi"},
    {country: "Uganda", code: "256", label: "ug"},
    {country: "Ukraine", code: "380", label: "ua"},
    {country: "United Arab Emirates", code: "971", label: "ae"},
    {country: "United Kingdom", code: "44", label: "gb"},
    {country: "United States", code: "1", label: "us"},
    {country: "Uruguay", code: "598", label: "uy"},
    {country: "Uzbekistan", code: "998", label: "uz"},
    {country: "Vanuatu", code: "678", label: "vu"},
    {country: "Vatican City", code: "379", label: "va"},
    {country: "Venezuela", code: "58", label: "ve"},
    {country: "Vietnam", code: "84", label: "vn"},
    {country: "Western Sahara", code: "212", label: "eh"},
    {country: "Yemen", code: "967", label: "ye"},
    {country: "Zambia", code: "260", label: "zm"},
    {country: "Zimbabwe", code: "263", label: "zw"}
]
